=== F0rth/Phamm/DTD/phamm-plugins.dtd
<!-- ==========================================================================
  This is the DTD for Phamm plugins (draft).

  Copyright (c) 2005-2008 Alessandro De Zorzi <adezorzi AT rhx DOT it>

  URI for the DTD:
  http://www.phamm.org/DTD/phamm-plugins.dtd

  <!ENTITY % Boolean "(0 | 1)">
========================================================================== -->

<!ELEMENT plugin (label,version,author,license,shortDescription?,
			longDescription?,parent,color?,minAuthLevel,
			isDomainRelated,isPostmasterRelated,isAccountRelated,
			domain?,postmaster?,account?)>

<!ATTLIST plugin name CDATA #REQUIRED>

<!ELEMENT version (number,creationDate,updatedDate,status?)>

<!ELEMENT author (firstName,lastName,mail,web?)>

<!ELEMENT domain (objectClasses*,attributes*)>

<!ELEMENT postmaster (objectClasses*,attributes*)>

<!ELEMENT account (objectClasses?,attributes?)>

<!ELEMENT objectClasses (objectClass*)>

<!ELEMENT objectClass (bug)>

<!ATTLIST objectClass name CDATA #REQUIRED>

<!ELEMENT attributes (attribute*)>

<!ELEMENT attribute (size | maxlength | hidden | default | type | editable | bool | text | table | reverse | multiple | required | subordinated | subordinateddelete | subordinatedReverse | hidecreation | textarea | multiplier | prefix | suffix | minAuthLevel | cron | date | tablenoedit | options | prettyName)*>

<!ATTLIST attribute name CDATA #REQUIRED>

<!ELEMENT options (option+)>

<!ELEMENT option (value)>

<!ELEMENT label (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT shortDescription (#PCDATA)>
<!ELEMENT longDescription (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT minAuthLevel (#PCDATA)>
<!ELEMENT isDomainRelated (#PCDATA)>
<!ELEMENT isPostmasterRelated (#PCDATA)>
<!ELEMENT isAccountRelated (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT creationDate (#PCDATA)>
<!ELEMENT updatedDate (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT maxlength (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT editable (#PCDATA)>
<!ELEMENT bool (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT table (#PCDATA)>
<!ELEMENT bug (#PCDATA)>
<!ELEMENT reverse (#PCDATA)>
<!ELEMENT multiple (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT subordinated (#PCDATA)>
<!ELEMENT subordinateddelete (#PCDATA)>
<!ELEMENT subordinatedReverse (#PCDATA)>
<!ELEMENT hidecreation (#PCDATA)>
<!ELEMENT textarea (#PCDATA)>
<!ELEMENT multiplier (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT cron (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT tablenoedit (#PCDATA)>
<!ATTLIST option name CDATA #REQUIRED>
<!ELEMENT value (#PCDATA)>
<!ELEMENT prettyName (#PCDATA)>

=== F0rth/Phamm/plugins/jabber.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="jabber">
	<label>JABBER</label>
	<version>
		<number>0.0.1</number>
		<creationDate>2009-08-13</creationDate>
		<updatedDate>2009-08-13</updatedDate>
		<status>beta</status>
	</version>
	<author>
		<firstName>viva</firstName>
		<lastName>perversia</lastName>
		<mail>viva@perversia.net</mail>
		<web>http://perversia.net</web>
	</author>
	<license>GPL</license>
	<shortDescription>Plugin to manage jabber accounts</shortDescription>
	<longDescription>Plugin to manage jabber accounts</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>10</minAuthLevel>
	<isDomainRelated>0</isDomainRelated>
	<isPostmasterRelated>0</isPostmasterRelated>
	<isAccountRelated>1</isAccountRelated>
	
	<account>
		<objectClasses>
			<objectClass name="jabberAccount">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="jabberAccess">
				<prettyName>Jabber Access</prettyName>
				<table>1</table>
				<bool>1</bool>
				<required>1</required>
				<default>TRUE</default>
			</attribute>
			<attribute name="jabberID">
				<prettyName>Jabber-ID</prettyName>
				<editable>1</editable>
				<required>1</required>
				<default>=php.Value(+account_new+,@,%domain%)</default>
			</attribute>
		</attributes>
	</account>
</plugin>

=== F0rth/Phamm/plugins/davical.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="davical">
	<label>DAViCal</label>
	<version>
		<number>0.0.1</number>
		<creationDate>2009-09-02</creationDate>
		<updatedDate>2009-09-02</updatedDate>
		<status>beta</status>
	</version>
	<author>
		<firstName>viva</firstName>
		<lastName>perversia</lastName>
		<mail>viva@perversia.net</mail>
		<web>http://perversia.net</web>
	</author>
	<license>GPL</license>
	<shortDescription>Plugin to manage DAViCal accounts</shortDescription>
	<longDescription>Plugin to manage DAViCal accounts</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>10</minAuthLevel>
	<isDomainRelated>0</isDomainRelated>
	<isPostmasterRelated>0</isPostmasterRelated>
	<isAccountRelated>1</isAccountRelated>
	
	<account>
		<objectClasses>
			<objectClass name="CalDavAccount">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="CalDavAccess">
				<prettyName>CalDav Access</prettyName>
				<table>1</table>
				<bool>1</bool>
				<required>1</required>
				<default>TRUE</default>
			</attribute>
		</attributes>
	</account>
</plugin>

=== F0rth/Phamm/plugins/alias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="alias">
	<label>ALIAS</label>
	<version>
		<number>0.0.3</number>
		<creationDate>2006-09-22</creationDate>
		<updatedDate>2008-09-08</updatedDate>
		<status>stable</status>
	</version>
	<author>
		<firstName>Alessandro De Zorzi</firstName>
		<lastName>De Zorzi</lastName>
		<mail>team@phamm.org</mail>
		<web>http://www.phamm.org</web>
	</author>
	<license>GPL</license>
	<shortDescription>Plugin to manage e-mail alias</shortDescription>
	<longDescription>Plugin to manage e-mail alias</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>2</minAuthLevel>
	<isDomainRelated>0</isDomainRelated>
	<isPostmasterRelated>0</isPostmasterRelated>
	<isAccountRelated>1</isAccountRelated>

	<account>
		<objectClasses>
			<objectClass name="VirtualMailAlias">
				<bug>0</bug>
			</objectClass>
			<objectClass name="amavisAccount">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="maildrop">
				<prettyName>Destination</prettyName>
				<table>1</table>
				<multiple>1</multiple>
			</attribute>
			<attribute name="accountActive">
				<prettyName>Active</prettyName>
				<bool>1</bool>
				<table>1</table>
				<default>TRUE</default>
				<minAuthLevel>4</minAuthLevel>
			</attribute>
			<attribute name="smtpAuth">
				<prettyName>SMTP Auth</prettyName>
				<bool>1</bool>
				<table>1</table>
				<default>FALSE</default>
				<minAuthLevel>4</minAuthLevel>
			</attribute>
			<attribute name="amavisBypassVirusChecks">
				<prettyName>Virus Check</prettyName>
				<bool>1</bool>
				<reverse>1</reverse>
				<default>TRUE</default>
				<minAuthLevel>4</minAuthLevel>
			</attribute>
			<attribute name="amavisBypassSpamChecks">
				<prettyName>SPAM Check</prettyName>
				<bool>1</bool>
				<reverse>1</reverse>
				<default>TRUE</default>
				<minAuthLevel>4</minAuthLevel>
			</attribute>
		</attributes>
	</account>
</plugin>

=== F0rth/Phamm/plugins/proxy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="proxy">
	<label>PROXY</label>
	<version>
		<number>0.0.3</number>
		<creationDate>2005-02-19</creationDate>
		<updatedDate>2008-09-08</updatedDate>
		<status>beta</status>
	</version>
	<author>
		<firstName>Alessandro De Zorzi</firstName>
		<lastName>De Zorzi</lastName>
		<mail>team@phamm.org</mail>
		<web>http://www.phamm.org</web>
	</author>
	<license>GPL</license>
	<shortDescription>Plugin to manage proxy accounts</shortDescription>
	<longDescription>Plugin to manage proxy accounts (Squid...)</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>10</minAuthLevel>
	<isDomainRelated>0</isDomainRelated>
	<isPostmasterRelated>0</isPostmasterRelated>
	<isAccountRelated>1</isAccountRelated>
	
	<account>
		<objectClasses>
			<objectClass name="proxyAccount">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="webAccess">
				<prettyName>Web Access</prettyName>
				<table>1</table>
				<bool>1</bool>
				<default>TRUE</default>
			</attribute>
			<attribute name="proxyHost">
				<prettyName>Proxy Host</prettyName>
				<table>1</table>
			</attribute>
		</attributes>
	</account>
</plugin>

=== F0rth/Phamm/plugins/ftp.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="ftp">
	<label>FTP</label>
	<version>
		<number>0.0.2</number>
		<creationDate>2005-02-19</creationDate>
		<updatedDate>2008-09-08</updatedDate>
		<status>beta</status>
	</version>
	<author>
		<firstName>Alessandro De Zorzi</firstName>
		<lastName>De Zorzi</lastName>
		<mail>team@phamm.org</mail>
		<web>http://www.phamm.org</web>
	</author>
	<license>GPL</license>
	<shortDescription>Plugin to manage pure-FTP</shortDescription>
	<longDescription>Plugin to manage pure-FTP</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>10</minAuthLevel>

	<isDomainRelated>1</isDomainRelated>
	<isPostmasterRelated>1</isPostmasterRelated>
	<isAccountRelated>0</isAccountRelated>
	<postmaster>
		<objectClasses>
			<objectClass name="posixAccount">
				<bug>0</bug>
			</objectClass>
			<objectClass name="PureFTPdUser">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="gidNumber">
				<prettyName>GID number</prettyName>
				<editable>1</editable>
				<required>1</required>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
			<attribute name="homeDirectory">
				<prettyName>Home Directory</prettyName>
				<editable>1</editable>
				<required>1</required>
				<default>=php.Value(%domain%,/mnt/www/,+domain_new+)</default>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
			<attribute name="uid">
				<prettyName>UID</prettyName>
				<editable>1</editable>
				<required>1</required>
				<default>=php.Value(%domain%,,+domain_new+)</default>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
			<attribute name="uidNumber">
				<prettyName>UID Number</prettyName>
				<editable>1</editable>
				<required>1</required>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
			<attribute name="FTPStatus">
				<prettyName>FTP Status</prettyName>
				<table>1</table>
				<default>enabled</default>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
			<attribute name="FTPQuotaMBytes">
				<prettyName>FTP Quota Mb</prettyName>
				<size>4</size>
				<maxlength>4</maxlength>
				<default>50</default>
				<minAuthLevel>10</minAuthLevel>
			</attribute>
		</attributes>
	</postmaster>
</plugin>

=== F0rth/Phamm/plugins/person.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plugin SYSTEM "http://www.phamm.org/DTD/phamm-plugins.dtd">

<plugin name="person">
	<label>PERSON</label>
	<version>
		<number>0.0.3</number>
		<creationDate>2006-05-25</creationDate>
		<updatedDate>2008-09-08</updatedDate>
		<status>beta</status>
	</version>
	<author>
		<firstName>Alessandro De Zorzi</firstName>
		<lastName>De Zorzi</lastName>
		<mail>team@phamm.org</mail>
		<web>http://www.phamm.org</web>
	</author>
	<license>GPL</license>
	<shortDescription>RFC2798: Internet Organizational Person</shortDescription>
	<longDescription>RFC2798: Internet Organizational Person</longDescription>
	<parent>top</parent>
	<color>FF4455</color>
	<minAuthLevel>10</minAuthLevel>
	<isDomainRelated>0</isDomainRelated>
	<isPostmasterRelated>0</isPostmasterRelated>
	<isAccountRelated>1</isAccountRelated>
	
	<account>
		<objectClasses>
			<objectClass name="inetOrgPerson">
				<bug>0</bug>
			</objectClass>
		</objectClasses>
		<attributes>
			<attribute name="telephoneNumber">
				<prettyName>Telephone</prettyName>
				<table>1</table>
			</attribute>
			<attribute name="homePhone">
				<prettyName>Home Phone</prettyName>
				<table>1</table>
			</attribute>
			<attribute name="mobile">
				<prettyName>Mobile</prettyName>
				<table>1</table>
			</attribute>
			<attribute name="facsimileTelephoneNumber">
				<prettyName>FAX</prettyName>
				<table>1</table>
			</attribute>
			<attribute name="pager">
				<prettyName>Pager</prettyName>
				<table>1</table>
			</attribute>
		</attributes>
	</account>
</plugin>
